
files = \
	org.shr.phoneui.Dialer.xml \
	org.shr.phoneui.Contacts.xml \
	org.shr.phoneui.CallManagement.xml \
	org.shr.phoneui.Notification.xml \
	org.shr.phoneui.Messages.xml \
	org.shr.phoneui.PhoneLog.xml

include ../tools/rules.mk

