
files = \
	org.shr.phoneuid.Dialer.xml \
	org.shr.phoneuid.Contacts.xml \
	org.shr.phoneuid.CallManagement.xml \
	org.shr.phoneuid.Dialogs.xml \
	org.shr.phoneuid.Messages.xml \
	org.shr.phoneuid.PhoneLog.xml

include ../tools/rules.mk

