
files = \
	org.shr.ophonekitd.Dialer.xml \
	org.shr.ophonekitd.Contacts.xml \
	org.shr.ophonekitd.CallManagement.xml \
	org.shr.ophonekitd.Messages.xml \
	org.shr.ophonekitd.PhoneLog.xml

include ../tools/rules.mk

